// <auto-generated />
using System;
using Group1Flight.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Group1Flight.Migrations
{
    [DbContext(typeof(FlightContext))]
    partial class FlightContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Group1Flight.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AirlineId");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            AirlineId = 1,
                            ImageName = "aa_logo.png",
                            Name = "American Airlines"
                        },
                        new
                        {
                            AirlineId = 2,
                            ImageName = "emirates_logo.png",
                            Name = "Emirates"
                        },
                        new
                        {
                            AirlineId = 3,
                            ImageName = "cathay_logo.jpg",
                            Name = "Cathay Pacific"
                        },
                        new
                        {
                            AirlineId = 4,
                            ImageName = "jal_logo.png",
                            Name = "Japan Airlines"
                        },
                        new
                        {
                            AirlineId = 5,
                            ImageName = "af_logo.png",
                            Name = "Air France"
                        });
                });

            modelBuilder.Entity("Group1Flight.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AircraftType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("AirlineId")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("ArrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("CabinType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<double>("Emission")
                        .HasColumnType("REAL");

                    b.Property<string>("FlightCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            FlightId = 1,
                            AircraftType = "Boeing 737",
                            AirlineId = 1,
                            ArrivalTime = new TimeSpan(0, 0, 0, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 0, 0, 0, 0),
                            Emission = 120.5,
                            FlightCode = "AA101",
                            From = "Chicago",
                            Price = 150m,
                            To = "New York"
                        },
                        new
                        {
                            FlightId = 2,
                            AircraftType = "Airbus A380",
                            AirlineId = 2,
                            ArrivalTime = new TimeSpan(0, 0, 0, 0, 0),
                            CabinType = "Business",
                            Date = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 0, 0, 0, 0),
                            Emission = 450.0,
                            FlightCode = "EK202",
                            From = "Dubai",
                            Price = 850m,
                            To = "London"
                        },
                        new
                        {
                            FlightId = 3,
                            AircraftType = "Boeing 777",
                            AirlineId = 3,
                            ArrivalTime = new TimeSpan(0, 0, 0, 0, 0),
                            CabinType = "Economy Plus",
                            Date = new DateTime(2026, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 0, 0, 0, 0),
                            Emission = 380.19999999999999,
                            FlightCode = "CX303",
                            From = "Hong Kong",
                            Price = 1200m,
                            To = "San Francisco"
                        },
                        new
                        {
                            FlightId = 4,
                            AircraftType = "Boeing 787",
                            AirlineId = 4,
                            ArrivalTime = new TimeSpan(0, 0, 0, 0, 0),
                            CabinType = "Economy",
                            Date = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 0, 0, 0, 0),
                            Emission = 310.0,
                            FlightCode = "JL404",
                            From = "Los Angeles",
                            Price = 950m,
                            To = "Tokyo"
                        },
                        new
                        {
                            FlightId = 5,
                            AircraftType = "Airbus A320",
                            AirlineId = 5,
                            ArrivalTime = new TimeSpan(0, 0, 0, 0, 0),
                            CabinType = "Basic Economy",
                            Date = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartureTime = new TimeSpan(0, 0, 0, 0, 0),
                            Emission = 85.5,
                            FlightCode = "AF505",
                            From = "Paris",
                            Price = 110m,
                            To = "Rome"
                        });
                });

            modelBuilder.Entity("Group1Flight.Models.FlightNumber", b =>
                {
                    b.Property<string>("FlightNumberId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FlightNumberId");

                    b.ToTable("FlightNumbers");

                    b.HasData(
                        new
                        {
                            FlightNumberId = "FN001",
                            Name = "American Airlines"
                        });
                });

            modelBuilder.Entity("Group1Flight.Models.Flight", b =>
                {
                    b.HasOne("Group1Flight.Models.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Group1Flight.Models.Airline", b =>
                {
                    b.Navigation("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
